name: Test Goose Workflow

on:
  workflow_dispatch:

jobs:
  test-goose:
    uses: ./.github/workflows/cd-run-goose-migration-dev.yml
    with:
      migrations-dir: "./"
      secret-name: "RDSDoesNotExists"
    secrets:
      PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.GOOSE_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.GOOSE_AWS_SECRET_ACCESS_KEY }}
